### ISSUE TITLE
Add support for 256 for GitHub

### ISSUE THREAD

**Issue by alexellis** [alexellis/hmac#1]
I believe @burtonr tried to use this library for something other than GitHub and ran into an issue with needing SHA256 or similar.

This issue should look at what other schemes are desirable for HMAC use and implement them.

* Update the unit tests with a new example as per https://github.com/alexellis/hmac/blob/master/pkg_test.go#L40 but for a sha256 prefix
* Consider whether a new signature is required such as Validate256 Sign256, a new parameter Validate(shaLength, ...) or no breaking changes

**Comment by alexellis** [comment]
Example:

```
X-Hub-Signature-256: sha256=long-hash-here

```

**Comment by alexellis** [comment]
See also: https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads

**Comment by alexellis** [comment]
/add label: good first issue, help wanted

**Comment by nitishkumar71** [comment]
I will work on it.

**Comment by alexellis** [comment]
Thank you :pray: once you have a PR ready, we can get it released and then update Derek to consume it. https://github.com/alexellis/derek/issues/181
